id: I0540AA57
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-08-16T14:22:17.707365'
last_modified: '2022-08-16T14:22:17.707379'
parser: null
source_metadata:
  title: 'Śāntideva: Bodhicaryāvatāra'
  language: sa
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
